from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('partners','0002_contentitem'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='MemberProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80)),('birth_date',models.DateField(blank=True,null=True)),('gender',models.CharField(blank=True,choices=[('M','남성'),('F','여성'),('O','기타')],max_length=1)),('phone',models.CharField(blank=True,max_length=30)),('region',models.CharField(blank=True,max_length=40)),('address_detail',models.CharField(blank=True,max_length=250)),('privacy_agreed',models.BooleanField(default=False)),('regular_member_requested',models.BooleanField(default=False)),('membership_status',models.CharField(choices=[('general','일반회원'),('pending','정회원 승인대기'),('regular','정회원'),('withdrawn','탈퇴')],default='general',max_length=20)),('joined_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='member_profile',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='DogRegistration',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('dog_name',models.CharField(max_length=80)),('registration_no',models.CharField(blank=True,max_length=80)),('breed',models.CharField(blank=True,max_length=100)),('birth_date',models.DateField(blank=True,null=True)),('gender',models.CharField(blank=True,max_length=20)),('status',models.CharField(choices=[('pending','승인대기'),('approved','승인'),('rejected','반려')],default='pending',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='dogs',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='MemberBenefit',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=150)),('description',models.TextField(blank=True)),('valid_from',models.DateField(blank=True,null=True)),('valid_to',models.DateField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('sort_order',models.IntegerField(default=0))]),
      migrations.CreateModel(name='Inquiry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80)),('phone',models.CharField(blank=True,max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('subject',models.CharField(max_length=200)),('body',models.TextField()),('status',models.CharField(choices=[('new','신규'),('processing','처리중'),('done','답변완료')],default='new',max_length=20)),('admin_memo',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
    ]
