# Generated by Django 6.0.8 on 2026-10-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_content_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='경상남도 반려견 협회', max_length=120)),
                ('site_subtitle', models.CharField(blank=True, default='Gyeongnam Pet Dog Association', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='site/logo/')),
                ('hero_eyebrow', models.CharField(blank=True, default='GYEONGNAM PET DOG ASSOCIATION', max_length=200)),
                ('hero_title', models.CharField(default='믿을 수 있는\n반려견 협회', max_length=300)),
                ('hero_meta1', models.CharField(blank=True, default='고유번호 539-80-02508 · 대표자 심규진', max_length=300)),
                ('hero_meta2', models.CharField(blank=True, default='경남 창원시 성산구 용지로 159, iM뱅크(대구은행) 4층 405호', max_length=300)),
                ('hero_button1_text', models.CharField(blank=True, default='반려견 회원등록', max_length=80)),
                ('hero_button1_link', models.CharField(blank=True, default='#join', max_length=500)),
                ('hero_button2_text', models.CharField(blank=True, default='회원혜택', max_length=80)),
                ('hero_button2_link', models.CharField(blank=True, default='benefits.html', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '홈페이지 기본설정',
                'verbose_name_plural': '홈페이지 기본설정',
            },
        ),
    ]
