# Generated by Django 6.0.8 on 2026-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_about_media_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesetting',
            name='greeting_badge_bottom',
            field=models.IntegerField(default=-20),
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='greeting_badge_left',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='greeting_badge_radius',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='greeting_badge_text',
            field=models.CharField(default='대표자 심규진', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpagesetting',
            name='greeting_body',
            field=models.TextField(default='안녕하십니까, 경상남도 반려견 협회 홈페이지를 찾아주신 여러분께 진심으로 감사드립니다.\n\n저희 협회는 경상남도에 거주하는 반려견과 반려인들의 상호 권익을 도모하고, 살기 좋은 경상남도를 만들기 위한 공동의 노력을 통해 동물복지 향상에 이바지하고자 설립되었습니다.\n\n반려견 등록 지원, 교육·훈련 프로그램, 제휴 동물병원 의료 지원 등 다양한 사업을 통해 반려인으로서의 긍지를 실현하고, 비반려인과의 유대관계를 형성하는 데 앞장서겠습니다.\n\n앞으로도 회원 여러분과 함께 성장하는 협회가 되도록 최선을 다하겠습니다. 감사합니다.'),
        ),
        migrations.AlterField(
            model_name='aboutpagesetting',
            name='mission_desc',
            field=models.TextField(default='경상남도 반려견 협회는 반려견들과 비반려견인과의 친목과 단결을 도모하고, 이를 바탕으로 반려견 복지 향상에 기여하며, 반려인으로서의 긍지를 실현함과 비반려인과의 유대관계 형성을 목적으로 합니다.'),
        ),
        migrations.AlterField(
            model_name='aboutpagesetting',
            name='title_eyebrow',
            field=models.CharField(default='OVERVIEW OF THE COMPANION DOG\nASSOCIATION', max_length=250),
        ),
    ]
