# Generated by Django 6.0.8 on 2026-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_aboutpagesetting_greeting_badge_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='ad_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='광고 종료일'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ad_monthly_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='월 광고금액'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ad_payment_type',
            field=models.CharField(blank=True, choices=[('monthly', '월납'), ('annual', '연납')], default='', max_length=20, verbose_name='광고비 납부방식'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ad_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='광고 시작일'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_affiliated',
            field=models.BooleanField(default=False, verbose_name='협력업체'),
        ),
    ]
