# Generated by Django 6.0.8 on 2026-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partner_ad_end_date_partner_ad_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='kakao_javascript_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='카카오 JavaScript 키'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='kakao_rest_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='카카오 REST API 키'),
        ),
    ]
