# Generated by Django 6.0.8 on 2026-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_sitesetting_kakao_javascript_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='kakao_place_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='kakao_place_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
