# Generated by Django 6.0.8 on 2026-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_partner_kakao_place_id_partner_kakao_place_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(db_index=True, max_length=200, verbose_name='견종명')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='영문 견종명')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='URL 식별자')),
                ('fci_group', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='FCI 그룹')),
                ('fci_group_name', models.CharField(blank=True, max_length=250, verbose_name='FCI 그룹명')),
                ('fci_section', models.CharField(blank=True, max_length=250, verbose_name='FCI 섹션')),
                ('fci_standard_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='FCI 표준번호')),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='원산지')),
                ('patronage', models.CharField(blank=True, max_length=200, verbose_name='후원국/관리국')),
                ('use', models.TextField(blank=True, verbose_name='용도')),
                ('classification', models.TextField(blank=True, verbose_name='분류')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('history', models.TextField(blank=True, verbose_name='역사')),
                ('appearance', models.TextField(blank=True, verbose_name='외형')),
                ('temperament', models.TextField(blank=True, verbose_name='성격/기질')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('image', models.FileField(blank=True, null=True, upload_to='breeds/', verbose_name='대표 이미지')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='외부 이미지 URL')),
                ('image_source', models.CharField(blank=True, max_length=500, verbose_name='이미지 출처')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='자료 출처')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='원문 URL')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='원문 식별자')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='추가 데이터')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='공개')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='최종 수집일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '견종',
                'verbose_name_plural': '견종',
                'ordering': ['fci_group', 'sort_order', 'name_ko'],
                'indexes': [models.Index(fields=['fci_group', 'name_ko'], name='breed_group_name_idx')],
            },
        ),
    ]
