# Generated by Django 6.0.8 on 2026-10-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_dogbreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogbreed',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='coat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='disqualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='faults',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='gait',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='head',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='height_female',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='height_male',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='limbs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='neck',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='purpose_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='size_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='source_detail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='source_group_id',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='tail',
            field=models.TextField(blank=True),
        ),
    ]
