# Generated by Django 6.0.8 on 2026-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_boardcategory_boardpost_boardlike_boardcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='챗봇 사용')),
                ('ai_enabled', models.BooleanField(default=False, verbose_name='OpenAI 사용')),
                ('bot_name', models.CharField(default='경상남도 반려견 협회 챗봇', max_length=100, verbose_name='챗봇 이름')),
                ('greeting', models.TextField(default='안녕하세요! 경상남도 반려견 협회 챗봇입니다.\n협회 정보, 반려견 등록·예방접종·법령 등 무엇이든 물어보세요!', verbose_name='첫 인사말')),
                ('system_prompt', models.TextField(blank=True, default='당신은 경상남도 반려견 협회 공식 안내 챗봇입니다. 사용자에게 정확하고 친절하게 답변하세요. 확실하지 않은 정보는 추측하지 말고 협회 문의를 안내하세요.', verbose_name='AI 시스템 지침')),
                ('model_name', models.CharField(default='gpt-5-mini', max_length=100, verbose_name='OpenAI 모델')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='OpenAI API Key')),
                ('contact_button_text', models.CharField(default='☎ 협회 문의하기', max_length=100, verbose_name='문의 버튼 문구')),
                ('contact_phone', models.CharField(default='010-3556-8603', max_length=30, verbose_name='문의 전화번호')),
                ('bot_video', models.FileField(blank=True, null=True, upload_to='chatbot/', verbose_name='챗봇 영상')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
